<a href="https://colab.research.google.com/github/Kedrynez/Test_eLama/blob/main/sql_ex_postgres_in_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Install postgresql server
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# Setup a password `postgres` for username `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

 * Starting PostgreSQL 10 database server
   ...done.
ALTER ROLE


In [2]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

In [3]:
!wget https://sql-ex.ru/download/sql-ex-pg.sql

--2022-12-11 13:48:22--  https://sql-ex.ru/download/sql-ex-pg.sql
Resolving sql-ex.ru (sql-ex.ru)... 5.188.73.5, 2a00:ab00:1203:22:ce0:a1ff:fee0:bb42
Connecting to sql-ex.ru (sql-ex.ru)|5.188.73.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41053 (40K) [application/x-sql]
Saving to: ‘sql-ex-pg.sql.1’

sql-ex-pg.sql.1     100%[===================>]  40.09K  --.-KB/s    in 0s      

2022-12-11 13:48:23 (229 MB/s) - ‘sql-ex-pg.sql.1’ saved [41053/41053]



In [4]:
with open('/content/sql-ex-pg.sql', 'r') as file:
    sql = file.read()

In [5]:
con.execute(sql[1:])

In [6]:
import pandas as pd

In [7]:
def select(sql):
  return pd.read_sql(sql,con)

# База данных Компьютерная фирма

Схема БД состоит из четырех таблиц:
Product(maker, model, type)
PC(code, model, speed, ram, hd, cd, price)
Laptop(code, model, speed, ram, hd, price, screen)
Printer(code, model, color, type, price)
Таблица Product представляет производителя (maker), номер модели (model) и тип ('PC' - ПК, 'Laptop' - ПК-блокнот или 'Printer' - принтер). Предполагается, что номера моделей в таблице Product уникальны для всех производителей и типов продуктов. В таблице PC для каждого ПК, однозначно определяемого уникальным кодом – code, указаны модель – model (внешний ключ к таблице Product), скорость - speed (процессора в мегагерцах), объем памяти - ram (в мегабайтах), размер диска - hd (в гигабайтах), скорость считывающего устройства - cd (например, '4x') и цена - price (в долларах). Таблица Laptop аналогична таблице РС за исключением того, что вместо скорости CD содержит размер экрана -screen (в дюймах). В таблице Printer для каждой модели принтера указывается, является ли он цветным - color ('y', если цветной), тип принтера - type (лазерный – 'Laser', струйный – 'Jet' или матричный – 'Matrix') и цена - price.


# База данных "Корабли"


Рассматривается БД кораблей, участвовавших во второй мировой войне. Имеются следующие отношения:
Classes (class, type, country, numGuns, bore, displacement)
Ships (name, class, launched)
Battles (name, date)
Outcomes (ship, battle, result)
Корабли в «классах» построены по одному и тому же проекту, и классу присваивается либо имя первого корабля, построенного по данному проекту, либо названию класса дается имя проекта, которое не совпадает ни с одним из кораблей в БД. Корабль, давший название классу, называется головным.
Отношение Classes содержит имя класса, тип (bb для боевого (линейного) корабля или bc для боевого крейсера), страну, в которой построен корабль, число главных орудий, калибр орудий (диаметр ствола орудия в дюймах) и водоизмещение ( вес в тоннах). В отношении Ships записаны название корабля, имя его класса и год спуска на воду. В отношение Battles включены название и дата битвы, в которой участвовали корабли, а в отношении Outcomes – результат участия данного корабля в битве (потоплен-sunk, поврежден - damaged или невредим - OK).
Замечания. 1) В отношение Outcomes могут входить корабли, отсутствующие в отношении Ships. 2) Потопленный корабль в последующих битвах участия не принимает.

# База данных "Фирма вторсырья"


Фирма имеет несколько пунктов приема вторсырья. Каждый пункт получает деньги для их выдачи сдатчикам вторсырья. Сведения о получении денег на пунктах приема записываются в таблицу:
Income_o(point, date, inc)
Первичным ключом является (point, date). При этом в столбец date записывается только дата (без времени), т.е. прием денег (inc) на каждом пункте производится не чаще одного раза в день. Сведения о выдаче денег сдатчикам вторсырья записываются в таблицу:
Outcome_o(point, date, out)
В этой таблице также первичный ключ (point, date) гарантирует отчетность каждого пункта о выданных деньгах (out) не чаще одного раза в день.
В случае, когда приход и расход денег может фиксироваться несколько раз в день, используется другая схема с таблицами, имеющими первичный ключ code:
Income(code, point, date, inc)
Outcome(code, point, date, out)
Здесь также значения столбца date не содержат времени. 

# Задача №1. 

Найдите номер модели, скорость и размер жесткого диска для всех ПК стоимостью менее 500 дол. Вывести: model, speed и hd 

In [8]:
sql='''SELECT  t.model,
               t.speed,
               t.hd
FROM PC AS t
WHERE t.price < 500 '''

In [9]:
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

# Задача №2.

Найдите производителей принтеров. Вывести: maker 

In [10]:
sql='''SELECT DISTINCT t.maker
FROM product AS t
WHERE t.type ='Printer' 
'''

In [11]:
select(sql)

maker
0     A
1     D
2     E

# Задача №3.

Найдите номер модели, объем памяти и размеры экранов ПК-блокнотов, цена которых превышает 1000 дол.(№ модели по возрастанию)

In [12]:
sql='''SELECT t.model,
              t.ram,
              t.screen
FROM laptop AS t
WHERE t.price > 1000
ORDER BY t.model
'''

In [13]:
select(sql)

model  ram  screen
0  1298   64      15
1  1750  128      14
2  1752  128      14

# Задача №4.

Найдите все записи таблицы Printer для цветных принтеров. 

In [14]:
sql=''' SELECT *
FROM Printer
WHERE color = 'y'
'''

In [15]:
select(sql)

code model color type  price
0     2  1433     y  Jet  270.0
1     3  1434     y  Jet  290.0

# Задача №5.

Найдите номер модели, скорость и размер жесткого диска ПК, имеющих 12x или 24x CD и цену менее 600 дол.

In [16]:
sql="""SELECT model, speed, hd 	
FROM pc
WHERE (cd = '12x' OR cd ='24x')
AND price < 600
"""

In [17]:
select(sql)

model  speed    hd
0  1232    500  10.0
1  1232    450   8.0
2  1232    450  10.0
3  1260    500  10.0

# Задача №6.

Для каждого производителя, выпускающего ПК-блокноты c объёмом жесткого диска не менее 10 Гбайт, найти скорости таких ПК-блокнотов. Вывод: производитель, скорость. 

In [18]:
sql="""SELECT DISTINCT pr.maker,
              l.speed 	
FROM product AS pr LEFT JOIN laptop AS l ON pr.model=l.model
WHERE l.hd >= 10
ORDER BY 1,2
"""

In [19]:
select(sql)

maker  speed
0     A    450
1     A    600
2     A    750
3     B    750

# Задача №7.

Найдите номера моделей и цены всех имеющихся в продаже продуктов (любого типа) производителя B (латинская буква).


In [20]:
sql="""SELECT DISTINCT pr.model, 
               p.price
FROM product AS pr JOIN  pc AS p ON pr.model=p.model
WHERE pr.maker = 'B'
UNION
SELECT DISTINCT pr.model, 
               l.price
FROM product AS pr  JOIN  laptop AS l ON pr.model=l.model
WHERE pr.maker = 'B'
UNION
SELECT DISTINCT pr.model, 
               pri.price
FROM product AS pr  JOIN  printer AS pri ON pr.model=pri.model
WHERE pr.maker = 'B'
"""

In [21]:
select(sql)

model   price
0  1750  1200.0
1  1121   850.0

# Задача №8.

Найдите производителя, выпускающего ПК, но не ПК-блокноты. 

In [22]:
sql="""SELECT DISTINCT p.maker 
FROM product p
WHERE p.type ='PC'
EXCEPT 
SELECT DISTINCT p.maker
FROM product p
WHERE p.type ='Laptop'              
"""

In [23]:
select(sql)

maker
0     E

# Задача №9.

Найдите производителей ПК с процессором не менее 450 Мгц. Вывести: Maker 

In [24]:
sql="""SELECT DISTINCT t.maker
FROM product t JOIN pc p on t.model=p.model
WHERE p.speed >= 450
"""

In [25]:
select(sql)

maker
0     B
1     E
2     A

# Задача №10.

Найдите модели принтеров, имеющих самую высокую цену. Вывести: model, price 

In [26]:
sql="""SELECT p.model,
              p.price
FROM printer p 
WHERE p.price = (SELECT MAX(p.price)
                 FROM printer p)
"""

In [27]:
select(sql)

model  price
0  1276  400.0
1  1288  400.0

# Задача №11.

Найдите среднюю скорость ПК. 

In [28]:
sql="""SELECT AVG(p.speed)
FROM pc p 
"""

In [29]:
select(sql)

avg
0  608.333333

# Задача №12.

Найдите среднюю скорость ПК-блокнотов, цена которых превышает 1000 дол. 

In [30]:
sql="""SELECT AVG(l.speed)
FROM laptop l
WHERE l.price > 1000 
"""

In [31]:
select(sql)

avg
0  700.0

# Задача №13.

Найдите среднюю скорость ПК, выпущенных производителем A.

In [32]:
sql="""SELECT AVG(p.speed)
FROM pc p JOIN product t ON p.model=t.model
WHERE t.maker = 'A' 
"""

In [33]:
select(sql)

avg
0  606.25

# Задача №14.


Найдите класс, имя и страну для кораблей из таблицы Ships, имеющих не менее 10 орудий. 

In [34]:
sql="""SELECT c.class,
              s.name,
              c.country
FROM Classes c JOIN Ships s ON c.class=s.class
WHERE c.numGuns >=10
"""

In [35]:
select(sql)

class            name country
0       Tennessee      California     USA
1  North Carolina  North Carolina     USA
2       Tennessee       Tennessee     USA
3  North Carolina      Washington     USA
4  North Carolina    South Dakota     USA

#Задача №15.

Найдите размеры жестких дисков, совпадающих у двух и более PC. Вывести: HD 

In [36]:
sql="""SELECT hd
FROM pc p
GROUP BY hd
HAVING count(*) >=2
"""

In [37]:
select(sql)

hd
0   8.0
1  20.0
2   5.0
3  14.0
4  10.0

# Задача №16.

Найдите пары моделей PC, имеющих одинаковые скорость и RAM. В результате каждая пара указывается только один раз, т.е. (i,j), но не (j,i), Порядок вывода: модель с большим номером, модель с меньшим номером, скорость и RAM. 

In [38]:
sql="""SELECT DISTINCT p.model, t.model, p.speed, p.ram
FROM pc p, pc t
WHERE p.speed = t.speed AND p.ram = t.ram
AND p.model > t.model
"""

In [39]:
select(sql)

model model  speed  ram
0  1233  1121    750  128
1  1233  1232    500   64
2  1260  1232    500   32

#Задача №17.

Найдите модели ПК-блокнотов, скорость которых меньше скорости каждого из ПК.
Вывести: type, model, speed 

In [40]:
sql="""SELECT DISTINCT pr.type,
                       l.model, 
                       l.speed
FROM laptop l JOIN product pr ON l.model=pr.model
WHERE l.speed < ALL (SELECT p.speed FROM pc p)
"""

In [41]:
select(sql)

type model  speed
0  Laptop  1298    350

#Задача №18.

Найдите производителей самых дешевых цветных принтеров. Вывести: maker, price 

In [42]:
sql="""SELECT DISTINCT p.maker,
                       pr.price
FROM product p JOIN printer pr ON p.model=pr.model
WHERE pr.color = 'y' AND pr.price IN (SELECT MIN(pr.price)
                                      FROM printer pr
                                      WHERE pr.color = 'y')             
"""

In [43]:
select(sql)

maker  price
0     D  270.0

#Задача №19.

Для каждого производителя, имеющего модели в таблице Laptop, найдите средний размер экрана выпускаемых им ПК-блокнотов.
Вывести: maker, средний размер экрана

In [44]:
sql="""SELECT p.maker,
              AVG(l.screen)
FROM product p JOIN laptop l ON p.model=l.model
GROUP BY 1              
"""

In [45]:
select(sql)

maker   avg
0     B  14.0
1     C  12.0
2     A  13.0

#Задача №20.

Найдите производителей, выпускающих по меньшей мере три различных модели ПК. Вывести: Maker, число моделей ПК. 

In [46]:
sql=""" SELECT p.maker,
               COUNT(*)
FROM  product p
WHERE p.type = 'PC'
GROUP BY 1
HAVING COUNT(*) >=3
"""

In [47]:
select(sql)

maker  count
0     E      3

#Задача №21.

Найдите максимальную цену ПК, выпускаемых каждым производителем, у которого есть модели в таблице PC.
Вывести: maker, максимальная цена. 

In [48]:
sql="""SELECT t.maker,
              MAX(price)
FROM product t JOIN pc p ON t.model=p.model
GROUP BY 1
"""

In [49]:
select(sql)

maker    max
0     B  850.0
1     E  350.0
2     A  980.0

#Задача №22.

Для каждого значения скорости ПК, превышающего 600 МГц, определите среднюю цену ПК с такой же скоростью. Вывести: speed, средняя цена.

In [50]:
sql="""SELECT p.speed,
              AVG(p.price)
FROM pc p
WHERE p.speed > 600
GROUP BY 1
"""

In [51]:
select(sql)

speed    avg
0    900  980.0
1    750  900.0
2    800  970.0

#Задача №23.

Найдите производителей, которые производили бы как ПК
со скоростью не менее 750 МГц, так и ПК-блокноты со скоростью не менее 750 МГц.
Вывести: Maker 

In [52]:
sql="""SELECT DISTINCT t.maker
FROM product t JOIN pc p ON t.model=p.model
WHERE p.speed >= 750
INTERSECT
SELECT DISTINCT t.maker
FROM product t JOIN laptop l ON t.model=l.model
WHERE l.speed >= 750 
"""

In [53]:
select(sql)

maker
0     B
1     A

#Задача №24.

Перечислите номера моделей любых типов, имеющих самую высокую цену по всей имеющейся в базе данных продукции. 

In [54]:
sql="""
WITH  t AS
(SELECT  p.model,
               p.price
FROM pc p
UNION 
SELECT  l.model,
        l.price
FROM laptop l
UNION 
SELECT  pr.model,
        pr.price
FROM printer pr)
SELECT t.model
FROM t
WHERE t.price = (SELECT MAX(t.price)
FROM t)
"""

In [55]:
select(sql)

model
0  1750

#Задача №25.


Найдите производителей принтеров, которые производят ПК с наименьшим объемом RAM и с самым быстрым процессором среди всех ПК, имеющих наименьший объем RAM. Вывести: Maker 

In [56]:
sql="""
WITH t AS
(WITH t AS
(SELECT t.maker,
        p.speed
FROM product t JOIN pc p ON t.model=p.model
WHERE p.ram = (SELECT MIN(t.ram) from pc t))
SELECT t.maker
FROM t
WHERE t.speed = (SELECT MAX(t.speed) FROM t)) 
SELECT DISTINCT p.maker
FROM product p
WHERE p.type='Printer' AND p.maker IN (SELECT * FROM t)
"""

In [57]:
select(sql)

maker
0     A
1     E

#Задача №26.

Найдите среднюю цену ПК и ПК-блокнотов, выпущенных производителем A (латинская буква). Вывести: одна общая средняя цена. 

In [58]:
sql="""
WITH t AS
(SELECT p.price
FROM product t JOIN pc p ON t.model=p.model
WHERE t.maker = 'A'
UNION ALL
SELECT l.price
FROM product t JOIN laptop l ON t.model=l.model
WHERE t.maker = 'A')
SELECT AVG(price)
FROM t
"""

In [59]:
select(sql)

avg
0  754.166667

#Задача №27.

Найдите средний размер диска ПК каждого из тех производителей, которые выпускают и принтеры. Вывести: maker, средний размер HD. 

In [60]:
sql="""
WITH t AS
(SELECT t.maker, p.hd
FROM product t JOIN pc p ON t.model=p.model
WHERE t.maker IN  (SELECT DISTINCT t.maker
FROM product t
WHERE t.type = 'Printer'))
SELECT t.maker,
       AVG(t.hd)
FROM t
GROUP BY 1
"""

In [61]:
select(sql)

maker    avg
0     A  14.75
1     E  10.00

In [62]:
sql="""SELECT b.maker, AVG(a.hd)
FROM pc a JOIN product b ON a.model = b.model
WHERE b.maker IN (SELECT DISTINCT maker FROM product 
                  WHERE type = 'Printer')
GROUP BY b.maker
"""

In [63]:
select(sql)

maker    avg
0     A  14.75
1     E  10.00

#Задача №28.


Используя таблицу Product, определить количество производителей, выпускающих по одной модели. 

In [64]:
sql="""SELECT COUNT(*)
FROM (SELECT maker
FROM product
GROUP BY 1
HAVING COUNT(model) = 1) AS t
"""

In [65]:
select(sql)

count
0      1

#Задача №29.

В предположении, что приход и расход денег на каждом пункте приема фиксируется не чаще одного раза в день [т.е. первичный ключ (пункт, дата)], написать запрос с выходными данными (пункт, дата, приход, расход). Использовать таблицы Income_o и Outcome_o. 

In [66]:
sql="""SELECT *
FROM Income_o FULL JOIN Outcome_o USING(point, date)
ORDER BY 2 
"""

In [67]:
select(sql)

point       date      inc       out
0       1 2001-03-14      NaN  15348.00
1       1 2001-03-22  15000.0       NaN
2       2 2001-03-22  10000.0   1440.00
3       1 2001-03-23  15000.0       NaN
4       2 2001-03-24   1500.0       NaN
5       1 2001-03-24   3400.0   3663.00
6       1 2001-03-26      NaN   1221.00
7       1 2001-03-28      NaN   2075.00
8       1 2001-03-29      NaN   2004.00
9       2 2001-03-29      NaN   7848.00
10      2 2001-04-02      NaN   2040.00
11      1 2001-04-11      NaN   3195.04
12      1 2001-04-13   5000.0   4490.00
13      1 2001-04-27      NaN   3110.00
14      1 2001-05-11   4500.0   2530.00
15      3 2001-09-13  11500.0   1500.00
16      3 2001-09-14      NaN   2300.00
17      3 2001-10-02  18000.0       NaN
18      3 2002-09-16      NaN   2150.00

#Задача №30.

В предположении, что приход и расход денег на каждом пункте приема фиксируется произвольное число раз (первичным ключом в таблицах является столбец code), требуется получить таблицу, в которой каждому пункту за каждую дату выполнения операций будет соответствовать одна строка.
Вывод: point, date, суммарный расход пункта за день (out), суммарный приход пункта за день (inc). Отсутствующие значения считать неопределенными (NULL). 

In [96]:
sql="""
WITH a AS
(SELECT point, date, SUM(inc) AS income
FROM Income
GROUP BY point, date),
b AS
(SELECT point, date, SUM(out) AS outcome
FROM Outcome
GROUP BY point, date)
SELECT *
FROM b FULL JOIN a USING(point, date)
ORDER BY 1, 2
"""

In [97]:
select(sql)

point       date   outcome   income
0       1 2001-03-14  15348.00      NaN
1       1 2001-03-22       NaN  30000.0
2       1 2001-03-23       NaN  15000.0
3       1 2001-03-24   7163.00   7000.0
4       1 2001-03-26   1221.00      NaN
5       1 2001-03-28   2075.00      NaN
6       1 2001-03-29   4010.00      NaN
7       1 2001-04-11   3195.04      NaN
8       1 2001-04-13   4490.00  10000.0
9       1 2001-04-27   3110.00      NaN
10      1 2001-05-11   2530.00   4500.0
11      2 2001-03-22   2880.00  10000.0
12      2 2001-03-24       NaN   3000.0
13      2 2001-03-29   7848.00      NaN
14      2 2001-04-02   2040.00      NaN
15      3 2001-09-13   2700.00   3100.0
16      3 2001-09-14   1150.00      NaN

In [86]:
sql="""
"""

In [87]:
select(sql)

point       date       sum
0       1 2001-03-14  15348.00
1       1 2001-03-24   7163.00
2       1 2001-03-26   1221.00
3       1 2001-03-28   2075.00
4       1 2001-03-29   4010.00
5       1 2001-04-11   3195.04
6       1 2001-04-13   4490.00
7       1 2001-04-27   3110.00
8       1 2001-05-11   2530.00
9       2 2001-03-22   2880.00
10      2 2001-03-29   7848.00
11      2 2001-04-02   2040.00
12      3 2001-09-13   2700.00
13      3 2001-09-14   1150.00